config/routes.rb
AnaliseGastos::Application.routes.draw do

  resources :gastos

  root to: 'contribuintes#index'

  resources :contribuintes
end

app/models/configuracao.rb
class Configuracao < ActiveRecord::Base

end

app/models/contribuinte.rb
class Contribuinte < ActiveRecord::Base

  has_many :gastos

  def total
    self.gastos.sum(:valor)
  end

end

app/models/gasto.rb
#encoding: utf-8

class Gasto < ActiveRecord::Base
  belongs_to :contribuinte
  after_save :enviar_email

  def enviar_email

    ActionMailer::Base.smtp_settings = {
        :address => "smtp.gmail.com",
        :domain => "gmail.com",
        :port => 587,
        :user_name => "analisedegastos@gmail.com",
        :password => Configuracao.where(:chave => "senha.email").take!.valor,
        :authentication => "plain",
        :enable_starttls_auto => true
    }

    ActionMailer::Base.mail(
        :from => "analisedegastos@gmail.com",
        :to => Configuracao.where(:chave => "remetentes").take!.valor,
        :subject => "Atualizacao de gastos",
        :body => " Contribuinte: #{self.contribuinte.nome} \n Gasto: #{self.descricao} \n Valor: #{self.valor}")
    .deliver

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contribuintes_controller.rb
class ContribuintesController < ApplicationController
  before_action :set_contribuinte, only: [:show]

  def index
    @contribuintes = Contribuinte.all
  end

  def show
    session[:contribuinte_id] = @contribuinte.id
  end

  private
  def set_contribuinte
    @contribuinte = Contribuinte.find(params[:id])
  end
end

app/controllers/gastos_controller.rb
class GastosController < ApplicationController

  def new
    @gasto = Gasto.new
  end

  def create
    @gasto = Gasto.new(gasto_params)
    @gasto.contribuinte = Contribuinte.find(session[:contribuinte_id])
    @gasto.save
    redirect_to contribuinte_path @gasto.contribuinte
  end

  private
  def gasto_params
    params.require(:gasto).permit(:valor, :descricao)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contribuintes_helper.rb
module ContribuintesHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/views/contribuintes/_form.html.erb
<%= form_for(@contribuinte) do |f| %>
  <% if @contribuinte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribuinte.errors.count, "error") %> prohibited this contribuinte from being saved:</h2>

      <ul>
      <% @contribuinte.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contribuintes/edit.html.erb
<h1>Editing contribuinte</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribuinte %> |
<%= link_to 'Back', contribuintes_path %>

app/views/contribuintes/index.html.erb
<table class="tabela">
  <% @contribuintes.each do |contribuinte| %>
      <tr class="tr-contribuinte" url='<%= contribuinte_path contribuinte %>'>
        <td><%= contribuinte.nome %></td>
        <td>R<%= number_to_currency(contribuinte.total) %></td>
      </tr>
  <% end %>
  <tr>
    <td> <b>Total</b> </td>
    <td> <b> R<%=number_to_currency(Gasto.sum(:valor)) %> </b> </td>
  </tr>
</table>

app/views/contribuintes/new.html.erb
<h1>New contribuinte</h1>

<%= render 'form' %>

<%= link_to 'Back', contribuintes_path %>

app/views/contribuintes/show.html.erb
<h2 style="text-align: center">Gastos de <%= @contribuinte.nome %></h2>

<br>

<%= link_to 'Adicionar gasto', new_gasto_path, {:class => "adicionar-gasto"} %>

<br>

<table class="tabela">
  <thead>
  <tr>
    <th>Descrição</th>
    <th>Valor</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @contribuinte.gastos.each do |gasto| %>
      <tr>
        <td><%= gasto.descricao %></td>
        <td>R<%= number_to_currency(gasto.valor) %></td>
        <td><%= link_to 'Editar', edit_gasto_path(gasto) %></td>
        <td><%= link_to 'Excluir', gasto, method: :delete, data: {confirm: 'Tem certeza?'} %></td>
      </tr>
  <% end %>
  </tbody>
  <tfoot>
  <tr>
    <td><b>Total</b></td>
    <td><b>R<%= number_to_currency(@contribuinte.total) %></b></td>
    <td> </td>
    <td> </td>
  </tr>
  </tfoot>
</table>

app/views/gastos/_form.html.erb
<%= form_for(@gasto) do |f| %>
    <% if @gasto.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@gasto.errors.count, "error") %> prohibited this gasto from being saved:</h2>

          <ul>
            <% @gasto.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :descrição %>
      <br>
      <%= f.text_field :descricao %>
    </div>

    <br>

    <div class="field">
      <%= f.label :valor %>
      <br>
      <%= f.text_field :valor %>
    </div>

    <br>

    <div class="actions">
      <%= f.submit :Salvar %>
    </div>
<% end %>

app/views/gastos/edit.html.erb
<h1>Editar gasto</h1>

<%= render 'form' %>

app/views/gastos/index.html.erb
<h1>Gastos de <%= @contribuinte.nome %></h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Valor</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gastos.each do |gasto| %>
      <tr>
        <td><%= gasto.descricao %></td>
        <td><%= gasto.valor %></td>
        <td><%= link_to 'Edit', edit_gasto_path(gasto) %></td>
        <td><%= link_to 'Destroy', gasto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gasto', new_gasto_path %>

app/views/gastos/new.html.erb
<h1>Adicionar gasto</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Análise de gastos</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= link_to 'Início', root_path, {:class => "home"} %>

  <%= yield %>

</div>

</body>
</html>